.SUFFIXES: .cpp .o

OBJECTS = main.o memo.o

CXX = g++
CPPFLAGS = -c

TARGET = test

$(TARGET) : $(OBJECTS)
	$(CXX) -o $(TARGET) $(OBJECTS)
clean :
	rm -rf $(OBJECTS) $(TARGET)
main.o : main.cpp
memo.o : memo.cpp
